
#                                               Scores:                        Skills:                  Attacks:                                     Defences:
#STATS = ['Key Score',
#         'Hit Dice',
#         'Perception',
#         ['Fortitude', 'Reflex', 'Will'],
#         ['Skills', '+ INT mod'],
#         ['Unarmed', 'Simple', 'Martial', 'Special'],
#         ['Unarmored', 'Light', 'Medium', 'Heavy'],
#         'Class DC']


CLASSES = {"Alchemist" : [['Int'],
                          8,
                          'Trained',
                          ['Expert', 'Expert', 'Trained'],
                          ['Crafting', 'FREE', 'FREE', 'FREE'],
                          ['Trained', 'Trained', 'Untrained', {'alchmical bombs': 'Trained'}],
                          ['Trained', 'Trained', 'Trained', 'Untrained'],
                          'alchemist'],
           "Barbarian" : [['Str'],
                          12,
                          'Expert',
                          ['Expert', 'Trained', 'Expert'],
                          ['Athletics', 'FREE', 'FREE', 'FREE'],
                          ['Trained', 'Trained', 'Trained', {}],
                          ['Trained', 'Trained', 'Trained', 'Untrained'],
                          'barbarian'],
           "Bard" : [["Cha"],
                     8,
                    'Expert',
                    ['Trained', 'Trained', 'Expert'],
                    ['Occultism', 'Performance'],
                    ['Trained', 'Trained', 'Untrained', {'longsword':'Trained', 'rapier':'Trained', 'sap': 'Trained', 'shortbow': 'Trained', 'shortsword': 'Trained', 'whip':'Trained'}],
                     ['Trained', 'Trained', 'Untrained', 'Untrained'],
                     'occult'],
           "Champion" : [['Str', 'Dex'],
                         10,
                         'Trained',
                         ['Expert', 'Trained', 'Expert'],
                         ['Religion', 'FREE', 'FREE', 'FREE'],
                         ['Trained', 'Trained', 'Trained', {}],
                         ['Trained', 'Trained', 'Trained', 'Trained'],
                         'divine'],
           "Cleric" : [['Wis'],
                       8,
                       'Trained',
                       ['Trained', 'Trained', 'Expert'],
                       ['Religion', 'FREE', 'FREE', 'FREE'],
                       ['Trained', 'Trained', {'deity':'Trained'}],
                       ['Trained', 'Untrained', 'Untrained', 'Untrained'],
                       'divine'],
           "Druid" : [['Wis'],
                      8,
                      'Trained',
                      ['Trained', 'Trained', 'Expert'],
                      ['Nature', 'FREE', 'FREE'],
                      ['Trained', 'Trained', 'Untrained', {}],
                      ['Trained', 'Trained', 'Trained', 'Untrained'],
                      'primal'],
           "Fighter" : [['Str', 'Dex'],
                        10,
                        'Expert',
                        ['Expert', 'Expert', 'Trained'],
                        ['FREE', 'FREE', 'FREE'],
                        ['Expert', 'Expert', 'Expert', {'advanced':'Trained'}],
                        ['Trained', 'Trained', 'Trained', 'Trained'],
                        'fighter'],
           "Monk" : [['Str', 'Dex'],
                     10,
                     'Trained',
                     ['Expert', 'Expert', 'Expert'],
                     ['FREE', 'FREE', 'FREE', 'FREE',],
                     ['Trained', 'Trained', 'Untrained', {}],
                     ['Expert', 'Untrained', 'Untrained', 'Untrained'],
                     'monk'],
           "Ranger" : [['Str', 'Dex'],
                       10,
                       'Expert',
                       ['Expert', 'Expert', 'Trained'],
                       ['Nature', 'Survival', 'FREE', 'FREE', 'FREE', 'FREE'],
                       ['Trained', 'Trained', 'Trained', {}],
                       ['Trained', 'Trained', 'Trained', 'Untrained'],
                       'ranger'],
           "Rogue" : [['Dex', 'Str', 'Cha'],
                      8,
                      'Expert',
                      ['Trained', 'Expert', 'Trained'],
                      ['Stealth', 'FREE', 'FREE', 'FREE', 'FREE', 'FREE', 'FREE', 'FREE'],
                      ['Trained', 'Trained', 'Untrained', {'rapier': 'Trained', 'sap':'Trained', 'shortbow':'Trained', 'shortsword':'Trained'}],
                      ['Trained', 'Trained', 'Untrained', 'Untrained'],
                      'rogue'],
           "Sorcerer" : [['Cha'],
                         6,
                         'Trained',
                         ['Trained', 'Trained', 'Expert'],
                         ['FREE', 'FREE'],
                         ['Trained', 'Trained', 'Untrained', {}],
                         ['Trained', 'Untrained', 'Untrained', 'Untrained'],
                         'bloodline'],
           "Wizard" : [['Int'],
                       6,
                       'Trained',
                       ['Trained', 'Trained', 'Expert'],
                       ['Arcana', 'FREE', 'FREE'],
                       ['Trained', 'Untrained', 'Untrained', {'club':'Trained', 'crossbow':'Trained', 'dagger':'Trained', 'heavy crossbow':'Trained', 'staff':'Trained'}],
                       ['Trained', 'Untrained', 'Untrained', 'Untrained'],
                       'arcane'],
           }

LEVELING = {"Alchemist" : [
 [],
 ['Ancestry and Background', 'Initial Proficiencies', 'Alchemy', 'Formula Book', 'Research Field',
  'Alchemist Feat'],
 ['Alchemist Feat', 'Skill Feat'],
 ['General Feat', 'Skill Increase'],
 ['Alchemist Feat', 'Skill Feat'],
 ['Ablility Boost', 'Ancestry Feat', 'Field Discovery', 'Powerful Alchemy', 'Skill Increase'],
 ['Alchemist Feat', 'Skill Feat'],
 ['Alchemical Weapon Expertise', 'General Feat', 'Iron Will', 'Perpetual Infusions', 'Skill Increase'],
 ['Alchemist Feat', 'Skill Feat'],
 ['Alchemical Expertise', 'Alertness', 'Ancestry Feat', 'Double Brew', 'Skill Increase'],
 ['Ability Boosts', 'Alchemist Feat', 'Skill Feat'],
 ['General Feat', 'Juggernaut', 'Perpetual Potency', 'Skill Increase'],
 ['Alchemist Feat', 'Skill Feat'],
 ['Ancestry Feat', 'Greater Field Discovery', 'Light Armor Expertise', 'Skill Increase',
  'Weapon Specialization'],
 ['Alchemist Feat', 'Skill Feat'],
 ['Ability Boosts', 'Alchemical Alacrity', 'Evasion', 'General Feat', 'Skill Increase'],
 ['Alchemist Feat', 'Skill Feat'],
 ['Alchemical Mastery', 'Ancestry Feat', 'Perpetual Perfection', 'Skill Increase'],
 ['Alchemist Feat', 'Skill Feat'],
 ['General Feat', 'Light Armor Mastery', 'Skill Increase'],
 ['Ability Boosts', 'Alchemical Feat', 'Skill Feat']
],
    "Barbarian" : [],
    "Bard" : [],
    "Champion" : [],
    "Cleric" : [],
    "Druid" : [],
    "Fighter" : [],
    "Monk" : [],
    "Ranger" : [],
    "Rogue" : [],
    "Sorcerer" : [],
    "Wizard" : [],
           }

